package com.rocketFoodDelivery.rocketFood.dtos.address;

// Jackson - JSON field mapping
import com.fasterxml.jackson.annotation.JsonProperty;

// Jakarta EE - Validation
import jakarta.validation.constraints.NotBlank;

// Lombok - Code generation
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Data Transfer Object for the Address table.
 * Used for both API input (create/update request bodies) and API output (responses).
 * Exposes only the fields defined in the API contract — internal timestamps are omitted.
 */
@Getter
@Setter
@AllArgsConstructor // this annotation generates a constructor with parameters for all fields, which is useful for creating instances of this DTO when we have all the data available (e.g., when converting from an entity to a DTO).
@NoArgsConstructor // this annotation is needed for Jackson to deserialize JSON into this DTO. deserialize means converting JSON data into a Java object. Jackson uses the no-args constructor to create an instance of the class before populating its fields with the data from the JSON. If there is no no-args constructor, Jackson will throw an exception when it tries to deserialize JSON into this DTO. NoArgs means that the generated constructor will have no parameters, allowing for the creation of an empty instance of the class. Useful for frameworks that require a default constructor, such as Jackson for JSON deserialization.
public class ApiAddressDTO {

    // Response-only: generated by the database, not sent by the client on create
    private int id;

    @NotBlank(message = "Street address is required")
    @JsonProperty("street_address")
    private String streetAddress;

    @NotBlank(message = "City is required")
    private String city;

    @NotBlank(message = "Postal code is required")
    @JsonProperty("postal_code")
    private String postalCode;
}
