package com.rocketFoodDelivery.rocketFood.repository;


// Spring Framework
import com.rocketFoodDelivery.rocketFood.models.Address;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;


// Java standard library
import java.util.List;
import java.util.Optional;


// Repository interface that provides CRUD operations for database access
@Repository
public interface AddressRepository extends JpaRepository<Address, Integer> {
    // Spring Data JPA automatically implements CRUD operations inherited from JpaRepository.
    // save(), findAll(), findById(), deleteById()


    // ==================== Native SQL CRUD Queries ====================

    // CREATE - Insert a new address.
    // Positional binding (?1..?3) because the arguments are not annotated with @Param.
    // created_on / update_on are set with NOW() because native SQL bypasses @CreationTimestamp.
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        INSERT INTO addresses (street_address, city, postal_code, created_on, update_on)
        VALUES (?1, ?2, ?3, NOW(), NOW())
    """)
    void saveAddress(String streetAddress, String city, String postalCode);


    // READ - Find all addresses. SELECT * maps every column back onto the Address entity.
    @Query(nativeQuery = true, value = """
        SELECT * FROM addresses
    """)
    List<Address> findAllAddresses();


    // READ - Find address by ID. Named binding (:addressId) because the argument uses @Param.
    @Query(nativeQuery = true, value = """
        SELECT * FROM addresses WHERE id = :addressId
    """)
    Optional<Address> findAddressById(@Param("addressId") int addressId);


    // UPDATE - Update an address by ID.
    // Positional binding: ?1 = addressId, ?2 = streetAddress, ?3 = city, ?4 = postalCode.
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        UPDATE addresses
        SET street_address = ?2, city = ?3, postal_code = ?4, update_on = NOW()
        WHERE id = ?1
    """)
    void updateAddress(int addressId, String streetAddress, String city, String postalCode);


    // DELETE - Delete an address by ID. Named binding (:addressId) because the argument uses @Param.
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        DELETE FROM addresses WHERE id = :addressId
    """)
    void deleteAddressById(@Param("addressId") int addressId);


    // GET - Get the id generated by the most recent INSERT on this connection.
    // Used right after saveAddress() to return the new address id in the create response.
    @Query(nativeQuery = true, value = """
        SELECT LAST_INSERT_ID()
    """)
    int getLastInsertedId();
}
