package com.rocketFoodDelivery.rocketFood.repository;


// Spring Framework
import com.rocketFoodDelivery.rocketFood.models.CourierStatus;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;


// Java standard library
import java.util.List;
import java.util.Optional;


// Repository interface that provides CRUD operations for database access
@Repository
public interface CourierStatusRepository extends JpaRepository <CourierStatus, Integer> {
    // Spring Data JPA automatically implements CRUD operations inherited from JpaRepository.
    // save(), findAll(), findById(), deleteById()


    // ==================== Native SQL CRUD Queries ====================

    // CREATE - Insert a new courier status.
    // Positional binding (?1); created_on / update_on set with NOW() (native SQL bypasses @CreationTimestamp).
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        INSERT INTO courier_statuses (name, created_on, update_on)
        VALUES (?1, NOW(), NOW())
    """)
    void saveCourierStatus(String name);


    // READ - Find all courier statuses. SELECT * maps every column back onto the entity.
    @Query(nativeQuery = true, value = """
        SELECT * FROM courier_statuses
    """)
    List<CourierStatus> findAllCourierStatuses();


    // READ - Find courier status by ID. Named binding (:courierStatusId) because the argument uses @Param.
    @Query(nativeQuery = true, value = """
        SELECT * FROM courier_statuses WHERE id = :courierStatusId
    """)
    Optional<CourierStatus> findCourierStatusById(@Param("courierStatusId") int courierStatusId);


    // UPDATE - Update a courier status by ID. Positional binding: ?1 = courierStatusId, ?2 = name.
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        UPDATE courier_statuses
        SET name = ?2, update_on = NOW()
        WHERE id = ?1
    """)
    void updateCourierStatus(int courierStatusId, String name);


    // DELETE - Delete a courier status by ID. Named binding (:courierStatusId) because the argument uses @Param.
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        DELETE FROM courier_statuses WHERE id = :courierStatusId
    """)
    void deleteCourierStatusById(@Param("courierStatusId") int courierStatusId);


    // GET - Get the id generated by the most recent INSERT on this connection.
    @Query(nativeQuery = true, value = """
        SELECT LAST_INSERT_ID()
    """)
    int getLastInsertedId();
}
