package com.rocketFoodDelivery.rocketFood.repository;


// Spring Framework
import com.rocketFoodDelivery.rocketFood.models.Courier;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;


// Java standard library
import java.util.List;
import java.util.Optional;


// Repository interface that provides CRUD operations for database access
@Repository
public interface CourierRepository extends JpaRepository <Courier, Integer> {
    // Spring Data JPA automatically implements CRUD operations inherited from JpaRepository.
    // save(), findAll(), findById(), deleteById()


    // ==================== Native SQL CRUD Queries ====================

    // CREATE - Insert a new courier.
    // Positional binding (?1..?5); no active parameter, so new couriers are always active = true.
    // created_on / update_on set with NOW() because native SQL bypasses @CreationTimestamp.
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        INSERT INTO couriers (user_id, address_id, courier_status_id, phone, email, active, created_on, update_on)
        VALUES (?1, ?2, ?3, ?4, ?5, true, NOW(), NOW())
    """)
    void saveCourier(int userId, int addressId, int courierStatusId, String phone, String email);


    // READ - Find all couriers. SELECT * maps every column back onto the Courier entity.
    @Query(nativeQuery = true, value = """
        SELECT * FROM couriers
    """)
    List<Courier> findAllCouriers();


    // READ - Find courier by ID. Named binding (:courierId) because the argument uses @Param.
    @Query(nativeQuery = true, value = """
        SELECT * FROM couriers WHERE id = :courierId
    """)
    Optional<Courier> findCourierById(@Param("courierId") int courierId);


    // READ - Find courier by user ID (lookup used to resolve a user's courier role).
    @Query(nativeQuery = true, value = """
        SELECT * FROM couriers WHERE user_id = :userId
    """)
    Optional<Courier> findCourierByUserId(@Param("userId") int userId);


    // UPDATE - Update a courier by ID.
    // Positional binding: ?1 = courierId, ?2 = courierStatusId, ?3 = phone, ?4 = email, ?5 = active.
    // user_id and address_id are intentionally NOT updated (immutable after creation).
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        UPDATE couriers
        SET courier_status_id = ?2, phone = ?3, email = ?4, active = ?5, update_on = NOW()
        WHERE id = ?1
    """)
    void updateCourier(int courierId, int courierStatusId, String phone, String email, boolean active);


    // DELETE - Delete a courier by ID. Named binding (:courierId) because the argument uses @Param.
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        DELETE FROM couriers WHERE id = :courierId
    """)
    void deleteCourierById(@Param("courierId") int courierId);


    // GET - Get the id generated by the most recent INSERT on this connection.
    @Query(nativeQuery = true, value = """
        SELECT LAST_INSERT_ID()
    """)
    int getLastInsertedId();
}
