package com.rocketFoodDelivery.rocketFood.repository;


// Spring Framework
import com.rocketFoodDelivery.rocketFood.models.Customer;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;


// Java standard library
import java.util.List;
import java.util.Optional;


// Repository interface that provides CRUD operations for database access
@Repository
public interface CustomerRepository extends JpaRepository <Customer, Integer> {
    // Spring Data JPA automatically implements CRUD operations inherited from JpaRepository.
    // save(), findAll(), findById(), deleteById()


    // ==================== Native SQL CRUD Queries ====================

    // CREATE - Insert a new customer.
    // Positional binding (?1..?4); no active parameter, so new customers are always active = true.
    // created_on / update_on set with NOW() because native SQL bypasses @CreationTimestamp.
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        INSERT INTO customers (user_id, address_id, phone, email, active, created_on, update_on)
        VALUES (?1, ?2, ?3, ?4, true, NOW(), NOW())
    """)
    void saveCustomer(int userId, int addressId, String phone, String email);


    // READ - Find all customers. SELECT * maps every column back onto the Customer entity.
    @Query(nativeQuery = true, value = """
        SELECT * FROM customers
    """)
    List<Customer> findAllCustomers();


    // READ - Find customer by ID. Named binding (:customerId) because the argument uses @Param.
    @Query(nativeQuery = true, value = """
        SELECT * FROM customers WHERE id = :customerId
    """)
    Optional<Customer> findCustomerById(@Param("customerId") int customerId);


    // READ - Find customer by user ID (lookup used to resolve a user's customer role).
    @Query(nativeQuery = true, value = """
        SELECT * FROM customers WHERE user_id = :userId
    """)
    Optional<Customer> findCustomerByUserId(@Param("userId") int userId);


    // UPDATE - Update a customer by ID.
    // Positional binding: ?1 = customerId, ?2 = phone, ?3 = email, ?4 = active.
    // user_id and address_id are intentionally NOT updated (immutable after creation).
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        UPDATE customers
        SET phone = ?2, email = ?3, active = ?4, update_on = NOW()
        WHERE id = ?1
    """)
    void updateCustomer(int customerId, String phone, String email, boolean active);


    // DELETE - Delete a customer by ID. Named binding (:customerId) because the argument uses @Param.
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        DELETE FROM customers WHERE id = :customerId
    """)
    void deleteCustomerById(@Param("customerId") int customerId);


    // GET - Get the id generated by the most recent INSERT on this connection.
    @Query(nativeQuery = true, value = """
        SELECT LAST_INSERT_ID()
    """)
    int getLastInsertedId();
}
