package com.rocketFoodDelivery.rocketFood.repository;


// Spring Framework
import com.rocketFoodDelivery.rocketFood.models.Employee;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;


// Java standard library
import java.util.List;
import java.util.Optional;


// Repository interface that provides CRUD operations for database access
@Repository
public interface EmployeeRepository extends JpaRepository <Employee, Integer> {
    // Spring Data JPA automatically implements CRUD operations inherited from JpaRepository.
    // save(), findAll(), findById(), deleteById()


    // ==================== Native SQL CRUD Queries ====================

    // CREATE - Insert a new employee.
    // Positional binding (?1..?4); created_on / update_on set with NOW() (native SQL bypasses @CreationTimestamp).
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        INSERT INTO employees (user_id, address_id, phone, email, created_on, update_on)
        VALUES (?1, ?2, ?3, ?4, NOW(), NOW())
    """)
    void saveEmployee(int userId, int addressId, String phone, String email);


    // READ - Find all employees. SELECT * maps every column back onto the Employee entity.
    @Query(nativeQuery = true, value = """
        SELECT * FROM employees
    """)
    List<Employee> findAllEmployees();


    // READ - Find employee by ID. Named binding (:employeeId) because the argument uses @Param.
    @Query(nativeQuery = true, value = """
        SELECT * FROM employees WHERE id = :employeeId
    """)
    Optional<Employee> findEmployeeById(@Param("employeeId") int employeeId);


    // READ - Find employee by user ID (lookup used to resolve a user's employee role).
    @Query(nativeQuery = true, value = """
        SELECT * FROM employees WHERE user_id = :userId
    """)
    Optional<Employee> findEmployeeByUserId(@Param("userId") int userId);


    // UPDATE - Update an employee by ID.
    // Positional binding: ?1 = employeeId, ?2 = phone, ?3 = email.
    // user_id and address_id are intentionally NOT updated (immutable after creation).
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        UPDATE employees
        SET phone = ?2, email = ?3, update_on = NOW()
        WHERE id = ?1
    """)
    void updateEmployee(int employeeId, String phone, String email);


    // DELETE - Delete an employee by ID. Named binding (:employeeId) because the argument uses @Param.
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        DELETE FROM employees WHERE id = :employeeId
    """)
    void deleteEmployeeById(@Param("employeeId") int employeeId);


    // GET - Get the id generated by the most recent INSERT on this connection.
    @Query(nativeQuery = true, value = """
        SELECT LAST_INSERT_ID()
    """)
    int getLastInsertedId();
}
