package com.rocketFoodDelivery.rocketFood.repository;


// Spring Framework
import com.rocketFoodDelivery.rocketFood.models.OrderStatus;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;


// Java standard library
import java.util.List;
import java.util.Optional;


// Repository interface that provides CRUD operations for database access
@Repository
public interface OrderStatusRepository extends JpaRepository <OrderStatus, Integer> {
    // Spring Data JPA automatically implements CRUD operations inherited from JpaRepository.
    // save(), findAll(), findById(), deleteById()


    // ==================== Native SQL CRUD Queries ====================

    // CREATE - Insert a new order status.
    // Positional binding (?1); created_on / update_on set with NOW() (native SQL bypasses @CreationTimestamp).
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        INSERT INTO order_statuses (name, created_on, update_on)
        VALUES (?1, NOW(), NOW())
    """)
    void saveOrderStatus(String name);


    // READ - Find all order statuses.
    @Query(nativeQuery = true, value = """
        SELECT * FROM order_statuses
    """)
    List<OrderStatus> findAllOrderStatuses();


    // READ - Find order status by ID. Named binding (:orderStatusId) because the argument uses @Param.
    @Query(nativeQuery = true, value = """
        SELECT * FROM order_statuses WHERE id = :orderStatusId
    """)
    Optional<OrderStatus> findOrderStatusById(@Param("orderStatusId") int orderStatusId);


    // READ - Find orderStatus by name
    @Query(value = """
            SELECT *
            FROM order_statuses
            WHERE name = :name
            """, nativeQuery = true)
    Optional<OrderStatus> findOrderStatusByName(@Param("name") String name);


    // UPDATE - Update an order status by ID. Positional binding: ?1 = orderStatusId, ?2 = name.
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        UPDATE order_statuses
        SET name = ?2, update_on = NOW()
        WHERE id = ?1
    """)
    void updateOrderStatus(int orderStatusId, String name);


    // DELETE - Delete an order status by ID. Named binding (:orderStatusId) because the argument uses @Param.
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        DELETE FROM order_statuses WHERE id = :orderStatusId
    """)
    void deleteOrderStatusById(@Param("orderStatusId") int orderStatusId);


    // GET - Get the id generated by the most recent INSERT on this connection.
    @Query(nativeQuery = true, value = """
        SELECT LAST_INSERT_ID()
    """)
    int getLastInsertedId();
}
