package com.rocketFoodDelivery.rocketFood.repository;


// Spring Framework
import com.rocketFoodDelivery.rocketFood.models.Order;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;


// Java standard library
import java.util.List;
import java.util.Optional;


// Repository interface that provides CRUD operations for database access
@Repository
public interface OrderRepository extends JpaRepository <Order, Integer> {
    // Spring Data JPA automatically implements CRUD operations inherited from JpaRepository.
    // save(), findAll(), findById(), deleteById()


    // ==================== Native SQL CRUD Queries ====================

    // CREATE - Insert a new order.
    // Positional binding (?1..?3); created_on / update_on set with NOW() (native SQL bypasses @CreationTimestamp).
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        INSERT INTO orders (restaurant_id, customer_id, order_status_id, created_on, update_on)
        VALUES (?1, ?2, ?3, NOW(), NOW())
    """)
    void saveOrder(int restaurantId, int customerId, int orderStatusId);


    // READ - Find all orders.
    @Query(nativeQuery = true, value = """
        SELECT * FROM orders
    """)
    List<Order> findAllOrders();


    // READ - Find order by ID. Named binding (:orderId) because the argument uses @Param.
    @Query(nativeQuery = true, value = """
        SELECT * FROM orders WHERE id = :orderId
    """)
    Optional<Order> findOrderById(@Param("orderId") int orderId);


    // READ - Find orders by restaurant ID.
    @Query(value = """
            SELECT * FROM orders WHERE restaurant_id = :restaurantId
            """, nativeQuery = true)
    List<Order> findOrdersByRestaurantId(@Param("restaurantId") int restaurantId);

    // READ - Find orders by customer ID.
    @Query(value = """
            SELECT * FROM orders WHERE customer_id = :customerId
            """, nativeQuery = true)
    List<Order> findOrdersByCustomerId(@Param("customerId") int customerId);

    // READ - Find orders by courier ID.
    @Query(value = """
            SELECT * FROM orders WHERE courier_id = :courierId
            """, nativeQuery = true)
    List<Order> findOrdersByCourierId(@Param("courierId") int courierId);


    // UPDATE - Update an order's status and restaurant rating by ID.
    // Positional binding: ?1 = orderId, ?2 = orderStatusId, ?3 = restaurantRating (nullable).
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        UPDATE orders
        SET order_status_id = ?2, restaurant_rating = ?3, update_on = NOW()
        WHERE id = ?1
    """)
    void updateOrder(int orderId, int orderStatusId, Integer restaurantRating);


    // UPDATE - Update only order status
    @Modifying
    @Transactional
    @Query(value = """
            UPDATE orders SET order_status_id = :orderStatusId WHERE id = :id
            """, nativeQuery = true)
    void updateOrderStatus(@Param("id") int id, @Param("orderStatusId") int orderStatusId);


    // DELETE - Delete an order by ID. Named binding (:orderId) because the argument uses @Param.
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        DELETE FROM orders WHERE id = :orderId
    """)
    void deleteOrderById(@Param("orderId") int orderId);


    // GET - Get the id generated by the most recent INSERT on this connection.
    @Query(nativeQuery = true, value = """
        SELECT LAST_INSERT_ID()
    """)
    int getLastInsertedId();
}
