package com.rocketFoodDelivery.rocketFood.repository;


// Spring Framework
import com.rocketFoodDelivery.rocketFood.models.ProductOrder;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;


// Java standard library
import java.util.List;
import java.util.Optional;


// Repository interface that provides CRUD operations for database access
@Repository
public interface ProductOrderRepository extends JpaRepository <ProductOrder, Integer> {
    // Spring Data JPA automatically implements CRUD operations inherited from JpaRepository.
    // save(), findAll(), findById(), deleteById()


    // ==================== Native SQL CRUD Queries ====================

    // CREATE - Insert a new product order.
    // Positional binding (?1..?4); created_on / update_on set with NOW() (native SQL bypasses @CreationTimestamp).
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        INSERT INTO product_orders (product_id, order_id, product_quantity, product_unit_cost, created_on, update_on)
        VALUES (?1, ?2, ?3, ?4, NOW(), NOW())
    """)
    void saveProductOrder(int productId, int orderId, int productQuantity, int productUnitCost);


    // READ - Find all product orders.
    @Query(nativeQuery = true, value = """
        SELECT * FROM product_orders
    """)
    List<ProductOrder> findAllProductOrders();


    // READ - Find product order by ID. Named binding (:productOrderId) because the argument uses @Param.
    @Query(nativeQuery = true, value = """
        SELECT * FROM product_orders WHERE id = :productOrderId
    """)
    Optional<ProductOrder> findProductOrderById(@Param("productOrderId") int productOrderId);


    // UPDATE - Update a product order by ID. Positional binding: ?1 = id, ?2 = quantity, ?3 = unit cost.
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        UPDATE product_orders
        SET product_quantity = ?2, product_unit_cost = ?3, update_on = NOW()
        WHERE id = ?1
    """)
    void updateProductOrder(int productOrderId, int productQuantity, int productUnitCost);


    // DELETE - Delete a product order by ID. Named binding (:productOrderId) because the argument uses @Param.
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        DELETE FROM product_orders WHERE id = :productOrderId
    """)
    void deleteProductOrderById(@Param("productOrderId") int productOrderId);


    // DELETE - Delete a productOrder by order ID
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        DELETE FROM product_orders WHERE order_id = :orderId
    """)
    void deleteProductOrdersByOrderId(@Param("orderId") int orderId);


    // GET - Get the id generated by the most recent INSERT on this connection.
    @Query(nativeQuery = true, value = """
        SELECT LAST_INSERT_ID()
    """)
    int getLastInsertedId();


    // ==================== Native SQL Business Rule Helper Queries ====================

    // COUNT - Check for duplicate product in the same order (excluding a specific ID)
    @Query(value = """
            SELECT COUNT(*) FROM product_orders
            WHERE order_id = :orderId AND product_id = :productId AND id != :excludeId
            """, nativeQuery = true)
    int countDuplicateProductOrder(@Param("productId") int productId, @Param("orderId") int orderId, @Param("excludeId") int excludeId);

    // READ - Get restaurant_id from a product
    @Query(value = """
            SELECT restaurant_id FROM products WHERE id = :productId
            """, nativeQuery = true)
    Integer findRestaurantIdByProductId(@Param("productId") int productId);

    // READ - Get restaurant_id from an order
    @Query(value = """
            SELECT restaurant_id FROM orders WHERE id = :orderId
            """, nativeQuery = true)
    Integer findRestaurantIdByOrderId(@Param("orderId") int orderId);
}
