package com.rocketFoodDelivery.rocketFood.repository;


import com.rocketFoodDelivery.rocketFood.models.Product;

// Spring Framework
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;


// Java standard library
import java.util.List;
import java.util.Optional;


// Repository interface that provides CRUD operations for database access
@Repository
public interface ProductRepository extends JpaRepository <Product, Integer> {
    // Spring Data JPA automatically implements CRUD operations inherited from JpaRepository.
    // save(), findAll(), findById(), deleteById()


    // ==================== Native SQL CRUD Queries ====================

    // CREATE - Insert a new product.
    // Positional binding (?1..?4); created_on / update_on set with NOW() (native SQL bypasses @CreationTimestamp).
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        INSERT INTO products (restaurant_id, name, description, cost, created_on, update_on)
        VALUES (?1, ?2, ?3, ?4, NOW(), NOW())
    """)
    void saveProduct(int restaurantId, String name, String description, int cost);


    // READ - Find all products. SELECT * maps every column back onto the Product entity.
    @Query(nativeQuery = true, value = """
        SELECT * FROM products
    """)
    List<Product> findAllProducts();


    // READ - Find product by ID. Named binding (:productId) because the argument uses @Param.
    @Query(nativeQuery = true, value = """
        SELECT * FROM products WHERE id = :productId
    """)
    Optional<Product> findProductById(@Param("productId") int productId);


    // READ - Find products by restaurant ID
    @Query(value = """
            SELECT *
            FROM products
            WHERE restaurant_id = :restaurantId
            """, nativeQuery = true)
    List<Product> findProductsByRestaurantId(@Param("restaurantId") int restaurantId);


    // UPDATE - Update a product by ID.
    // Positional binding: ?1 = productId, ?2 = name, ?3 = description, ?4 = cost.
    // restaurant_id is intentionally NOT updated (immutable after creation).
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        UPDATE products
        SET name = ?2, description = ?3, cost = ?4, update_on = NOW()
        WHERE id = ?1
    """)
    void updateProduct(int productId, String name, String description, int cost);


    // DELETE - Delete a product by ID. Named binding (:productId) because the argument uses @Param.
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        DELETE FROM products WHERE id = :productId
    """)
    void deleteProductById(@Param("productId") int productId);


    // GET - Get the id generated by the most recent INSERT on this connection.
    @Query(nativeQuery = true, value = """
        SELECT LAST_INSERT_ID()
    """)
    int getLastInsertedId();
}
