package com.rocketFoodDelivery.rocketFood.repository;


// Spring Framework
import com.rocketFoodDelivery.rocketFood.models.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;


// Java standard library
import java.util.List;
import java.util.Optional;


// Repository interface that provides CRUD operations for database access
@Repository
public interface UserRepository extends JpaRepository <User, Integer> {
    // Spring Data JPA automatically implements CRUD operations inherited from JpaRepository.
    // save(), findAll(), findById(), deleteById()


    // ==================== Native SQL CRUD Queries ====================

    // CREATE - Insert a new user.
    // Positional binding (?1..?3); created_on / update_on set with NOW() (native SQL bypasses @CreationTimestamp).
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        INSERT INTO users (name, email, password, created_on, update_on)
        VALUES (?1, ?2, ?3, NOW(), NOW())
    """)
    void saveUser(String name, String email, String password);


    // READ - Find all users. SELECT * maps every column back onto the User entity.
    @Query(nativeQuery = true, value = """
        SELECT * FROM users
    """)
    List<User> findAllUsers();


    // READ - Find user by ID. Named binding (:userId) because the argument uses @Param.
    @Query(nativeQuery = true, value = """
        SELECT * FROM users WHERE id = :userId
    """)
    Optional<User> findUserById(@Param("userId") int userId);


    // READ - Find user by email
    @Query(value = """
            SELECT *
            FROM users
            WHERE email = :email
            """, nativeQuery = true)
    Optional<User> findUserByEmail(@Param("email") String email);


    // UPDATE - Update a user by ID.
    // Positional binding: ?1 = userId, ?2 = name, ?3 = email, ?4 = password.
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        UPDATE users
        SET name = ?2, email = ?3, password = ?4, update_on = NOW()
        WHERE id = ?1
    """)
    void updateUser(int userId, String name, String email, String password);


    // DELETE - Delete a user by ID. Named binding (:userId) because the argument uses @Param.
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = """
        DELETE FROM users WHERE id = :userId
    """)
    void deleteUserById(@Param("userId") int userId);


    // GET - Get the id generated by the most recent INSERT on this connection.
    @Query(nativeQuery = true, value = """
        SELECT LAST_INSERT_ID()
    """)
    int getLastInsertedId();
}
