package com.rocketFoodDelivery.rocketFood.dtos.productOrder;

// Jackson - JSON field mapping
import com.fasterxml.jackson.annotation.JsonProperty;

// Jakarta EE - Validation
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;

// Lombok - Code generation
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Data Transfer Object for the ProductOrder join table.
 * Used for both API input (create/update request bodies) and API output (responses).
 * References product/order by id; internal timestamps are omitted.
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class ApiProductOrderDTO {

    // Response-only: generated by the database on create
    private int id;

    @JsonProperty("product_id")
    private int productId;

    @JsonProperty("order_id")
    private int orderId;

    @JsonProperty("product_quantity")
    @NotNull(message = "Product quantity is required")
    @Min(value = 1, message = "Product quantity must be at least 1")
    private Integer productQuantity;

    @JsonProperty("product_unit_cost")
    @NotNull(message = "Product unit cost is required")
    @Min(value = 0, message = "Product unit cost must be greater than or equal to 0")
    private Integer productUnitCost;
}
