package com.rocketFoodDelivery.rocketFood.dtos.courierStatus;

// Jakarta EE - Validation
import jakarta.validation.constraints.NotBlank;

// Lombok - Code generation
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Data Transfer Object for the CourierStatus table.
 * Used for both API input (create/update request bodies) and API output (responses).
 * Internal timestamps are omitted.
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class ApiCourierStatusDTO {

    // Response-only: generated by the database on create
    private int id;

    @NotBlank(message = "Status name is required")
    private String name;
}
