package com.rocketFoodDelivery.rocketFood.dtos.courier;

// Jackson - JSON field mapping
import com.fasterxml.jackson.annotation.JsonProperty;

// Jakarta EE - Validation
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;

// Lombok - Code generation
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Data Transfer Object for the Courier table.
 * Used for both API input (create/update request bodies) and API output (responses).
 * References users/addresses/courier_statuses by id; internal timestamps are omitted.
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class ApiCourierDTO {

    // Response-only: generated by the database on create
    private int id;

    @JsonProperty("user_id")
    private int userId;

    @JsonProperty("address_id")
    private int addressId;

    @JsonProperty("courier_status_id")
    private int courierStatusId;

    @NotBlank(message = "Phone is required")
    private String phone;

    @Email(message = "Email must be valid")
    private String email;

    private Boolean active;
}
