package com.rocketFoodDelivery.rocketFood.dtos.orderStatus;

// Jakarta EE - Validation
import jakarta.validation.constraints.NotBlank;

// Lombok - Code generation
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * CRUD Data Transfer Object for the OrderStatus table.
 * Used for the /api/order-statuses CRUD endpoints (request input and response output).
 * Distinct from ApiOrderStatusDTO ({status}), which is used by the custom order-status endpoint.
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class ApiOrderStatusCrudDTO {

    // Response-only: generated by the database on create
    private int id;

    @NotBlank(message = "Status name is required")
    private String name;
}
